name: check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: nohup Xvfb &
          echo "DISPLAY=:0" >> $GITHUB_ENV
      - run: yarn install
      - run: make -C node_modules/@mapwhit/tilerenderer prebuild
      - run: make check
